name: ci
on:
  - push
  - pull_request
jobs:
  test:
    name: Continuous integration (tests)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        loader: ["no-loader", "original", "patched"]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5

      - name: Install 📦
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --ignore-scripts
          useRollingCache: true

      - name: Test 🔬
        run: yarn test:${{ matrix.loader }}

